
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: interview-banking-pj
  tags:
    - microservice
  description: Entrevistas com os candidatos
  annotations:
    backstage.io/kubernetes-id: interview-banking-pj
    github.com/project-slug: "PicPay/interview-banking-pj"
    sonarqube.org/project-key: "PicPay_interview-banking-pj"
    newrelic.com/app-name: "interview-banking-pj"
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://picpay.atlassian.net/jira/software/c/projects/INVPJ/boards/10123
      title: Jira Board
      icon: dashboard
    - url: https://picpay.atlassian.net/wiki/spaces/SIP/pages/4761911498/RT+Cofrinhos
      title: Confluence Docs
      icon: dashboard
spec:
  lifecycle: production
  owner: group:default/investimentos-pj
  type: service
  providesApis:
      - interview-banking-pj-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: interview-banking-pj-api
  tags:
    - service
  description: |
    Entrevistas com os candidatos
  links:
    - url: https://picpay.atlassian.net/jira/software/c/projects/INVPJ/boards/10123
      title: Jira Board
      icon: dashboard
    - url: https://picpay.atlassian.net/wiki/spaces/SIP/pages/4761911498/RT+Cofrinhos
      title: Confluence Docs
      icon: dashboard
spec:
  lifecycle: production
  owner: group:default/investimentos-pj
  type: service
  definition:
    $text: ./docs/swagger.yaml
