spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order-book
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 0
      max-lifetime: 1800000
      idle-timeout: 600000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
